version: '3.7'
services:
  users:
    build: 
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8001:8000
    depends_on:
      - users_db
    networks:
      - app

  users_db:
    container_name: users_db
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: users
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata/emails:/var/lib/mysql
    ports:
      - 33068:3306
    networks:
      - app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma_user
    links:
      - users_db:users_db
    environment:
      PMA_HOST: users_db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    restart: always
    ports:
      - 8082:80
    networks:
      - app

networks:
  app: